name: Build

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    branches: [ local, local-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    -
      name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        cache: true
        go-version-file: 'go.mod'
    -
      name: Build
      run: go build ./cmd/2fa

    -
      name: Test
      run: go test ./...
