name: Build

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    branches: [ local, local-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    -
      name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        cache: true
        go-version-file: 'go.mod'
    -
      name: Build
      run: go build ./cmd/2fa

    -
      name: Test
      run: go test ./...
