name: Build

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    branches: [ local, local-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    -
      name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        cache: true
        go-version-file: 'go.mod'
    -
      name: Build
      run: go build ./cmd/2fa

    -
      name: Test
      run: go test ./...
