name: "Static Checks"

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ local, local-dev ]
#  schedule:
#    - cron: '35 10 10 * *'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    -
      id: setup_go
      name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        cache: false
        go-version-input:
        go-version-file: 'go.mod'
        repo-checkout: false
    -
      id: build
      name: Build
      if: ${{ !cancelled() && steps.setup_go.conclusion == 'success' }}
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 # v1.3.1
      if: ${{ !cancelled() && steps.build.conclusion == 'success' }}
      with:
        version: "2025.1.1"
        install-go: false
    -
      name: golangci-lint
      if: ${{ !cancelled() && steps.build.conclusion == 'success' }}
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: v2.9.0
        # skip-cache: true
        # Use a long invalidation interval, the go.mod hash is more likely to
        # change more frequently and force a cache invalidation anyway.
        cache-invalidation-interval: 60
