name: "Static Checks"

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ local, local-dev ]
#  schedule:
#    - cron: '35 10 10 * *'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit
    -
      name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    -
      id: setup_go
      name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
      with:
        cache: false
        go-version-input:
        go-version-file: 'go.mod'
        repo-checkout: false
    -
      id: build
      name: Build
      if: ${{ !cancelled() && steps.setup_go.conclusion == 'success' }}
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@024238d2898c874f26d723e7d0ff4308c35589a2 # v1.4.0
      if: ${{ !cancelled() && steps.build.conclusion == 'success' }}
      with:
        version: "2025.1.1"
        install-go: false
    -
      name: golangci-lint
      if: ${{ !cancelled() && steps.build.conclusion == 'success' }}
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: v2.9.0
        # skip-cache: true
        # Use a long invalidation interval, the go.mod hash is more likely to
        # change more frequently and force a cache invalidation anyway.
        cache-invalidation-interval: 60
