name: "Static Checks"

on:
  push:
    branches: [ local, local-dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ local, local-dev ]
#  schedule:
#    - cron: '35 10 10 * *'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Setup Go
      uses: actions/setup-go@v5
      with:
        cache: true
        check-latest: true
        go-version-file: 'go.mod'
    -
      id: govulncheck
      name: govulncheck
      uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4
      with:
        repo-checkout: false
        cache: false
    -
      name: Build
      run: go build ./...
    -
      name: staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      continue-on-error: true
      with:
        version: "2023.1.5"
        install-go: false
    -
      name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.54
        skip-cache: true
    # -
    #   name: GoKart
    #   continue-on-error: true
    #   run: |
    #     set -xue
    #     go install github.com/praetorian-inc/gokart@latest
    #     gokart scan -s -o gokart-results.sarif
    # -
    #   # Upload the SARIF file generated by GoKart
    #   name: Upload GoKart results
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: gokart-results.sarif
